# Generated by Django 4.0.5 on 2024-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('email', models.EmailField(default='', max_length=100, null=True)),
                ('address', models.TextField(max_length=100)),
                ('Mobile', models.BigIntegerField(default=1)),
            ],
        ),
    ]
